export const obstacleList = [
    "Overthinking",
    "Perfectionism",
    "Burnout",
    "Social media",
    "Gaming",
    "Streaming services",
    "Talking/texting",
    "Lack of direction",
    "Lack of interest",
    "Lack of peer support",
    "Noisy surroundings",
    "Limited time",
    "Over-reliance on tutorials",
    "Ineffective learning resources",
];